operand_1 = float(input("Введите первое число "))
operand_2 = float(input("Введите второе число "))
operand_3 = float(input("Введите третье число "))
print ("Сума ваших чисел равна: " operand_1 + operand_2 + operand_3)
print ("Произведение ваших чисел равно: " operand_1 * operand_2 * operand_3)
